services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: travel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: test@123456
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
